---
- name: Create the webshare network
  community.docker.docker_network:
    name: webshare

- name: Create project directory
  ansible.builtin.file:
    path: /srv/docker-compose/web
    state: directory
    mode: '0755'

- name: Copy docker compose files
  ansible.builtin.copy:
    src: files/{{ item }}
    dest: /srv/docker-compose/web/{{ item }}
    mode: 0644
  loop:
    - docker-compose.yml
    - proxy.conf

# - name: Deploy docker compose stack
#   community.docker.docker_compose:
#     project_src: /srv/docker-compose/web/
#     files:
#       - docker-compose.yml
#     remove_orphans: true
- name: Deploy docker compose stack
  ansible.builtin.shell:
    cmd: docker compose up -d --remove-orphans
    chdir: /srv/docker-compose/web/
