---
- name: Check SSH port
  import_playbook: ssh.yaml
- name: Deploy forgejo
  hosts: production
  roles:
    - reverse-proxy
    - forgejo-dc
    # Woodpecker was replaced by Forgejo Actions.
    - woodpecker-dc
    - minio-dc
  become: true
  vars:
    instance_url: "{{prod_url}}"
    woodpecker_mode: "woodpecker_production.yml"
